<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="9" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-09T10:14:47 IST" name="Suite" finished-at="2024-06-09T10:15:33 IST" duration-ms="46121">
    <groups>
      <group name="Purchase">
        <method signature="TestFrameWork.submitOrder(java.util.HashMap)[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" name="submitOrder" class="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork"/>
      </group> <!-- Purchase -->
      <group name="Errorhandling">
        <method signature="loginErrorValidationsTest.submitOrder()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" name="submitOrder" class="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest"/>
      </group> <!-- Errorhandling -->
    </groups>
    <test started-at="2024-06-09T10:14:47 IST" name="TestFrameWork" finished-at="2024-06-09T10:15:32 IST" duration-ms="45009">
      <class name="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:14:49 IST" name="launchApplication" finished-at="2024-06-09T10:14:59 IST" duration-ms="9910" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:14:59 IST" name="submitOrder" data-provider="getData" finished-at="2024-06-09T10:15:09 IST" duration-ms="10239" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sunnysun@1, product=ZARA COAT 3, email=synny@email.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:15:09 IST" name="tearDown" finished-at="2024-06-09T10:15:12 IST" duration-ms="3101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:15:12 IST" name="launchApplication" finished-at="2024-06-09T10:15:18 IST" duration-ms="5891" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:15:18 IST" name="submitOrder" data-provider="getData" finished-at="2024-06-09T10:15:24 IST" duration-ms="5505" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Nand@1234, product=ADIDAS ORIGINAL, email=nand@email.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:15:24 IST" name="tearDown" finished-at="2024-06-09T10:15:25 IST" duration-ms="1076" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:15:25 IST" name="launchApplication" finished-at="2024-06-09T10:15:27 IST" duration-ms="2395" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:15:27 IST" name="orderHistoryTest" finished-at="2024-06-09T10:15:31 IST" depends-on-methods="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork.submitOrder" duration-ms="4045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork@b3a43258]" started-at="2024-06-09T10:15:31 IST" name="tearDown" finished-at="2024-06-09T10:15:32 IST" duration-ms="1235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.TestFrameWork -->
    </test> <!-- TestFrameWork -->
    <test started-at="2024-06-09T10:14:47 IST" name="loginErrorValidationTest" finished-at="2024-06-09T10:15:33 IST" duration-ms="46121">
      <class name="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:14:47 IST" name="launchApplication" finished-at="2024-06-09T10:15:00 IST" duration-ms="12419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:00 IST" name="productErrorValidation" finished-at="2024-06-09T10:15:06 IST" duration-ms="6408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:06 IST" name="tearDown" finished-at="2024-06-09T10:15:08 IST" duration-ms="2142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:08 IST" name="launchApplication" finished-at="2024-06-09T10:15:13 IST" duration-ms="4463" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="submitOrder()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:13 IST" name="submitOrder" finished-at="2024-06-09T10:15:17 IST" duration-ms="4243" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest.submitOrder(loginErrorValidationsTest.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:586)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1595)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:17 IST" name="tearDown" finished-at="2024-06-09T10:15:18 IST" duration-ms="812" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:18 IST" name="launchApplication" finished-at="2024-06-09T10:15:21 IST" duration-ms="3219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="submitOrder()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:21 IST" name="submitOrder" finished-at="2024-06-09T10:15:23 IST" duration-ms="1429" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest.submitOrder(loginErrorValidationsTest.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:586)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1595)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:23 IST" name="tearDown" finished-at="2024-06-09T10:15:23 IST" duration-ms="503" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:23 IST" name="launchApplication" finished-at="2024-06-09T10:15:27 IST" duration-ms="3652" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:27 IST" name="submitOrder" finished-at="2024-06-09T10:15:30 IST" duration-ms="3462" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest.submitOrder(loginErrorValidationsTest.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:586)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1595)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest@fb0ca11c]" started-at="2024-06-09T10:15:31 IST" name="tearDown" finished-at="2024-06-09T10:15:33 IST" duration-ms="2708" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest -->
    </test> <!-- loginErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
